### ISSUE TITLE
Add Support for User Family Members

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1584]
**Is your feature request related to a problem? Please describe.**

1. To be even more useful to Administrators, there needs to be the ability to group Users as members of the same family.
2. When implemented in the API, the Admin Portal will be able to visualize and edit the family group members of each user in the user profile page.

**Describe the solution you'd like**
1. We should have the ability to add, and remove people from families. 
1. Families can only be valid if there are more than one member. Therefore when:
    1. there is only one member in a group, the family group entry should be empty
    2. a new family is created, the family group instantaneously has two family members
1. Other functionality must not be affected
1. You must write tests to validate your work

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- Work with @xoldyckk on evaluating your solution here and in the subsequent PR
- This may be a prerequisite for our menu of project ideas for GSoC 2024

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by monkCommits** [comment]
Please assign me this issue.

**Comment by monkCommits** [comment]
Hey, do you want me to write the api in one of the existing files or should I create a new one for it?

**Comment by palisadoes** [comment]
Follow the standard

**Comment by monkCommits** [comment]
@xoldyckk Hey could you please help me with this issue- 
1 What exactly should I return as the api end point. 
2 Could you give me a high level idea about how to start solving this issue. 
Thankyou, that is all,

**Comment by xoldyckk** [comment]
@monkCommits judging by your question it seems you aren't familiar with graphql? knowledge of graphql is a prerequisite to contribute to much of the logic within talawa-api

**Comment by monkCommits** [comment]
@xoldyckk  Yeah thats true, I have experience with writing express APIs though. Can I take a few days to learn Graphql and come back to this?

**Comment by palisadoes** [comment]
@monkCommits

1. This was assigned to you 9 days ago and there has been no PR with suitable code. Our policy is to reassign issues with no activity after 10 days. Waiting a few more days will only delay the completion of this issue which is a dependency on new screen issues we are about to create.
2. Please become familiar with graphQL and try to get assigned at that time. There will be many more API feature issues that will be created.

Unassigning

**Comment by AdityaRaimec22** [comment]
can I get assigned to this issue.

**Comment by shreyashidabral** [comment]
@palisadoes Can I work on this issue

**Comment by Tarunmeena0901** [comment]
i had worked with graphql before, may be I can work on this issue ........ if u allow me to take 3rd issue (my other two are in review )
@palisadoes

**Comment by Anubhav-2003** [comment]
@palisadoes Can I work on this issue. I know GraphQL, and only have one issue assigned, which is also almost complete. Also I intend to work on improvising the static file handeling of the API. So being able to work and familiarize myself with the grpahQL schema would help me immensenly in future issues that would involve the schema,.

**Comment by palisadoes** [comment]
> @palisadoes  can I get assigned to this issue. I know graphql very well.
> 

You have no commit history in your profile and this issue needs someone either with GraphQL knowledge or a proven interest in coding.

**Comment by palisadoes** [comment]
> @palisadoes Can I work on this issue
> 

You have no commit history in your profile and this issue needs someone either with GraphQL knowledge or a proven interest in coding.

**Comment by palisadoes** [comment]
@Anubhav-2003

I made a error in my assessment as I was using the Git mobile app. I've assigned the issue to @AdityaRaimec22

**Comment by palisadoes** [comment]
@AdityaRaimec22
@shreyashidabral 

I previously made the comment which was incorrect.

```
You have no commit history in your profile and this issue needs someone either with GraphQL knowledge or a proven interest in coding.
```

I was using my Git mobile app which didn't allow me to see your extensive git contributions. I apologize for the statement. It was unfounded.

**Comment by Anubhav-2003** [comment]
@palisadoes no problem sir.

**Comment by AdityaRaimec22** [comment]
@palisadoes can you please guide me in what can be the possible reason beyond the issue that I am facing. The issue I am facing after taking a pull from the develop branch. I don't have any clue how this error originated

```
[1] [SUCCESS] Generate outputs
[1]   ℹ Watching for changes...
[0] d:\Desktop\talawa-api\src\directives\directiveTransformer\authDirectiveTransformer.ts:19
[0]         const { resolve = defaultFieldResolver } = fieldConfig;
[0]                           ^
[0]
[0]
[0] ReferenceError: defaultFieldResolver is not defined
[0]     at MapperKind.OBJECT_FIELD (d:\Desktop\talawa-api\src\directives\directiveTransformer\authDirectiveTransformer.ts:19:27)
[0]     at mapFields (d:\Desktop\talawa-api\node_modules\@graphql-tools\utils\cjs\mapSchema.js:146:37)      
[0]     at mapSchema (d:\Desktop\talawa-api\node_modules\@graphql-tools\utils\cjs\mapSchema.js:10:37)       
[0]     at authDirectiveTransformer (d:\Desktop\talawa-api\src\directives\directiveTransformer\authDirectiveTransformer.ts:7:10)
[0]     at loadPlugins (d:\Desktop\talawa-api\src\index.ts:34:10)
[0]     at Object.<anonymous> (d:\Desktop\talawa-api\src\index.ts:140:13)
[0]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[0]     at Object.j (D:\Desktop\talawa-api\node_modules\tsx\dist\cjs\index.cjs:1:1197)
[0]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[0]     at Module._load (node:internal/modules/cjs/loader:960:12)
[0]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
[0]     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
[0]
[0] Node.js v18.17.0

```

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 Have you verified the version of Node.js you are using? It should be 20.

**Comment by palisadoes** [comment]
You bypassed the lint rules some how and now everyone else is having linting issues. Please resubmit your changes with the correct linting applied.
