### ISSUE TITLE
[BUG]: `import:sample-data` script ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by Chaitanya-Shahare** [PalisadoesFoundation/talawa-api#1679]
**Describe the bug**

- when running the script with `npm run import:sample-data`, it throws the error ERR_REQUIRE_ESM 
- Issue with requiring ECMAScript module 'nanoid'

**To Reproduce**

1. run `rpm run import:sample-data` in the project's root folder
2. it'll throw and error similar to following
```
> talawa-api@1.0.0 import:sample-data
> ts-node ./src/utilities/loadSampleData.ts

/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/nanoid/index.js from /Users/chaitanyashahare/Documents/opensource/talawa-api/src/libraries/requestTracing.ts not supported.
Instead change the require of index.js in /Users/chaitanyashahare/Documents/opensource/talawa-api/src/libraries/requestTracing.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/src/libraries/requestTracing.ts:20:18)
    at m._compile (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/src/libraries/logger.ts:9:26)
    at m._compile (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/src/libraries/index.ts:31:14)
    at m._compile (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/src/db.ts:18:21)
    at m._compile (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/src/utilities/loadSampleData.ts:19:14)
    at m._compile (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/chaitanyashahare/Documents/opensource/talawa-api/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Expected behavior**

- sample data must be imported in the local database

**Actual behavior**

- throws an error and there is no import

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/108579856/969cb3b0-242a-4667-b587-bccaaf45064c)

**Comment by Chaitanya-Shahare** [comment]
Can you please assign this issue to me?

**Comment by palisadoes** [comment]
@Chaitanya-Shahare. This is the probable cause as identified by @Doraemon012
- https://github.com/PalisadoesFoundation/talawa-api/pull/1632#issuecomment-1890408735
- The dependabot PR that caused this cannot be automatically reverted.

**Comment by palisadoes** [comment]
@Chaitanya-Shahare. There have also been schema changes that will cause the data importation to fail. This will need to be fixed too as noted by @Azad99-9
- https://github.com/PalisadoesFoundation/talawa/pull/2322#issuecomment-1890647988

**Comment by git-init-priyanshu** [comment]
Hey @palisadoes, I've got a solution that doesn't mess with any dependencies. Instead of downgrading  `nanoid`, I fixed it by doing what the error message says - using dynamic import for the `nanoid` package.
If this solution sounds good then I would be happy to work on this. Thanks.

**Comment by palisadoes** [comment]
@git-init-priyanshu Open an issue and ask to be assigned

**Comment by git-init-priyanshu** [comment]
> @git-init-priyanshu Open an issue and ask to be assigned

I have reopened my issue. #1705
