### ISSUE TITLE
Cannot register as LAST_RESORT_SUPERADMIN_EMAIL

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2165]
**Describe the bug**

You cannot register using the LAST_RESORT_SUPERADMIN_EMAIL email address

**To Reproduce**

1. Use the latest API and Admin `develop` code
2. Run the API setup
   1.  Set the LAST_RESORT_SUPERADMIN_EMAIL
   1. Install the sample data database
5. Start the API and Admin
6. You cannot register using the LAST_RESORT_SUPERADMIN_EMAIL email address

**Expected behavior**

**Actual behavior**

API Logs

```
[0] error 2024-04-06 08:14:26 k31ed6d2cg Field "UserInput.selectedOrganization" of required type "ID!" was not provided. {"locations":[{"line":3,"column":11}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","stacktrace":["GraphQLError: Field \"UserInput.selectedOrganization\" of required type \"ID!\" was not provided.","    at Object.ObjectValue (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:64:13)","    at Object.enter (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/graphql/language/visitor.js:197:21)","    at validate (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/graphql/validation/validate.js:91:24)","    at processGraphQLRequest (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/@apollo/server/src/requestPipeline.ts:247:40)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at internalExecuteOperation (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/@apollo/server/src/ApolloServer.ts:1313:12)","    at runHttpQuery (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/@apollo/server/src/runHttpQuery.ts:232:27)","    at runPotentiallyBatchedHttpQuery (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/@apollo/server/src/httpBatching.ts:85:12)","    at ApolloServer.executeHTTPGraphQLRequest (/home/peter/code/GitHub/PalisadoesFoundation/talawa-api/node_modules/@apollo/server/src/ApolloServer.ts:1087:14)"]}} 
[0] info 2024-04-06 08:14:26 k31ed6d2cg ::1 - - [06/Apr/2024:15:14:26 +0000] "POST /graphql/ HTTP/1.1" 400 158 9.270 ms  
```

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/beaebc27-f409-416e-80c3-cd806b916621)

**Additional details**

This may be related to:

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1440
2. https://github.com/PalisadoesFoundation/talawa-api/pull/2143

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
@palisadoes would like to solve this.

**Comment by palisadoes** [comment]
Please write a test to make sure the `LAST_RESORT_SUPERADMIN_EMAIL` can always register. This was supposed to have been fixed before, but now it's broken.

These are possibly related issues.

1. https://github.com/PalisadoesFoundation/talawa-api/issues/2048
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1768

**Comment by adi790uu** [comment]
1. @palisadoes got the exact issue but need some help there is a selectedOrganization argument which the signup api mutation is using which is not being passed from the frontend I would like to know what is the exact use of this argument in this mutation.

2. From the code it looks like it is making the user join an organization or create a membership request.

**Comment by adi790uu** [comment]
but a superAdmin does not require joining any organization, I have to separate the login for superAdmin

**Comment by palisadoes** [comment]
After some thought we should make the `LAST_RESORT_SUPERADMIN_EMAIL`  user select an organization on registration and we add them to just that organization in  `adminFor`, but also set `isSuperAdmin`. 

Is this how we handle an Admin or member being promoted to SuperAdmin currently? Or do we reset `adminFor`, but also set `isSuperAdmin`?

**Comment by Huy1996** [comment]
@adi790uu Are you still working on this?

**Comment by adi790uu** [comment]
Yeah I was busy so couldn't get to this but will finish this as soon as possible.

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by prashantrai-30** [comment]
Hey @palisadoes can i start working on it??

**Comment by prayanshchh** [comment]
when I tried to register using the LAST_RESORT_SUPERADMIN_EMAIL email address, a toast notifcation came "wait for admin approval"

is this the issue? (refer to pic)

![image](https://github.com/user-attachments/assets/c9f23e95-dbfc-470e-9e13-74ea5a54d757)

**Comment by palisadoes** [comment]
Closing. It looks like it's been fixed.
